<?php
include_once(__DIR__ . '/config/symbbase.php');
header('Content-Type: text/html; charset=UTF-8' );
?>
<!DOCTYPE html>
<html lang="<?php echo $GLOBALS['DEFAULT_LANG']; ?>">
    <?php
    include_once(__DIR__ . '/config/header-includes.php');
    ?>
    <head>
        <title><?php echo $GLOBALS['DEFAULT_TITLE']; ?> Home</title>
        <meta name="description" content="Welcome to the <?php echo $GLOBALS['DEFAULT_TITLE']; ?> portal">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/base.css?ver=<?php echo $GLOBALS['CSS_VERSION']; ?>" rel="stylesheet" type="text/css"/>
        <link href="css/main.css?ver=<?php echo $GLOBALS['CSS_VERSION']; ?>" rel="stylesheet" type="text/css"/>
        <meta name='keywords' content='' />
    </head>
    <body>
        <a class="screen-reader-only" href="#mainContainer" tabindex="0">Skip to main content</a>
        <?php
        include(__DIR__ . '/header.php');
        ?>
        <div id="mainContainer">
            <div class="q-pa-md">
                <h1 class="q-mb-md">Welcome to SeedTrack</h1>

                <div style="padding: 0 10px;">
                    This Symbiota based data access technology is being designed to provide many entrypoints for managing data
                    produced during the lifecycle of plant materials production. As a data management system, SeedTrack starts
                    by ingesting seed collection data and sorting all incoming data into a coherent data set that follows the
                    Seeds of Success data standard. SeedTrack will track records of those collections as they proceed through
                    curation and ex-situ conservation, get directed into container and other field seed production, before
                    tracking individual collections to specific outplanting and restoration sites. From Seed to Seed, SeedTrack
                    is a biological information system built to manage the massive amount of data generated by native seed supply
                    chains and enhance ecological restoration.
                </div>

                <div style="margin-top:10px;padding: 0 10px;">
                    SeedTrack uses an event-based architecture developed through the Advancing the Digitization of Biological
                    Collections effort by the National Science Foundation beginning around 2007. We take the many innovations
                    that have emerged from the thematic collection networks, like <a href="https://www.cal-ibis.org/index.php" target="_blank" tabindex="0">the Islands of the Californias Biodiversity Information System (Cal-IBIS)</a>
                    and <a href="https://irlspecies.org/index.php" target="_blank" tabindex="0">the Indian River Lagoon Species Inventory</a>, and apply
                    similar bioinformatics data management strategies to map out the seed supply chain and systematically
                    collect and organize the data generated by our collective production of seed to establish, moving from
                    the collection event, to its curation and eventual storage and characteristics about that storage and its
                    germination performance in ex-situ settings,  and provide a system that utilizes the Seeds of Success
                    protocol as its data standard.
                </div>

                <div style="margin-top:10px;padding: 0 10px;">
                    The module will be developed using existing functionality within Symbiota to track ex-situ plant and seed
                    collections, and add further functionality to track plant propagation methods used in growing events and
                    link those events to specimen based collections. The new data module will have the ability to be visible
                    to users who wish to incorporate the new plant conservation feature.
                </div>

                <div style="margin-top:10px;padding: 0 10px;">
                    The restoration module will be developed as an extension to the Symbiota biological informatics system to:
                    <ol start="1" type="1">
                        <li>Provide users (plant conservationists, seed collectors, data managers, curators, and researchers)
                            with a core data standard to track propagule specimen collections (primarily seed) and seedlings
                            in both cultivated and wild populations.
                        </li>
                        <li>Standardize data to assess the seed viability in disjunct species populations.</li>
                        <li>Track and share specimen collection events, propagation methodology, source native species plant
                            material, and document out-planted seedlings.</li>
                        <li>Allow for the tracking of changes that occur during the propagation and growing cycle such
                            as changes in fertilizer regime, changes in pot size, and plant mortality rate.</li>
                    </ol>
                </div>
            </div>
        </div>
        <?php
        include(__DIR__ . '/footer.php');
        include_once(__DIR__ . '/config/footer-includes.php');
        ?>
        <script>
            const homePageModule = Vue.createApp();
            homePageModule.use(Quasar, { config: {} });
            homePageModule.use(Pinia.createPinia());
            homePageModule.mount('#mainContainer');
        </script>
    </body>
</html>
