<?php
include_once(__DIR__ . '/config/symbbase.php');
header('Content-Type: text/html; charset=UTF-8' );
?>
<!DOCTYPE html>
<html lang="<?php echo $GLOBALS['DEFAULT_LANG']; ?>">
    <?php
    include_once(__DIR__ . '/config/header-includes.php');
    ?>
    <head>
        <title><?php echo $GLOBALS['DEFAULT_TITLE']; ?> Home</title>
        <meta name="description" content="Welcome to the <?php echo $GLOBALS['DEFAULT_TITLE']; ?> portal">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/base.css?ver=<?php echo $GLOBALS['CSS_VERSION']; ?>" rel="stylesheet" type="text/css"/>
        <link href="css/main.css?ver=<?php echo $GLOBALS['CSS_VERSION']; ?>" rel="stylesheet" type="text/css"/>
        <meta name='keywords' content='' />
    </head>
    <body>
        <a class="screen-reader-only" href="#mainContainer" tabindex="0">Skip to main content</a>
        <?php
        include(__DIR__ . '/header.php');
        ?>
        <div id="mainContainer">
            <div class="q-pa-md">
                <h1 class="q-mb-md">Welcome to SeedTrack</h1>

                <div style="padding: 0 10px;">
                    This is a seed data management system to manage the data produced at each step in the lifecycle of plant
                    materials production. SeedTrack tracks records of seed collections as they proceed from wildland collection
                    through curation and ex-situ conservation, are directed into container and other field seed production,
                    tracking individual collections to specific outplanting and restoration sites. From Seed to Seed, SeedTrack
                    is a biological information system built to manage the massive amount of data generated by native seed
                    supply chains to enhance the practice of ecological restoration.
                </div>

                <div style="margin-top:10px;padding: 0 10px;">
                    SeedTrack uses an event-based architecture developed through the Advancing the Digitization of Biological
                    Collections effort by the National Science Foundation beginning around 2007. We take the many innovations
                    that have emerged from the thematic collection networks, like <a href="https://www.cal-ibis.org/index.php" target="_blank" tabindex="0">the Islands of the Californias Biodiversity Information System (Cal-IBIS)</a>
                    and <a href="https://irlspecies.org/index.php" target="_blank" tabindex="0">the Indian River Lagoon Species Inventory</a>, and apply
                    similar bioinformatics data management strategies to map out the seed supply chain. The goal is to systematically
                    collect and organize data generated by the lifecycle of plant materials production, starting with the collection
                    event of the wildland source seed, to its curation and eventual storage. The system captures characteristics
                    about that storage, can capture germination performance in both ex-situ and in-situ restoration settings,
                    the propagation and agronomic qualities of the species, and eventually will have the ability to monitor
                    success of individual seed lots through long-term restoration site monitoring.
                </div>

                <div style="margin-top:10px;padding: 0 10px;">
                    SeedTrack is a modular system that uses the biological informatics functionality of Symbiota to track both
                    in-situ and ex-situ plant and seed collections across the many events in the plant materials lifecycle,
                    from seed to seed.
                </div>
            </div>
        </div>
        <?php
        include(__DIR__ . '/footer.php');
        include_once(__DIR__ . '/config/footer-includes.php');
        ?>
        <script>
            const homePageModule = Vue.createApp();
            homePageModule.use(Quasar, { config: {} });
            homePageModule.use(Pinia.createPinia());
            homePageModule.mount('#mainContainer');
        </script>
    </body>
</html>
