const useSpatialStore = Pinia.defineStore('spatial', {
    state: () => ({
        coreLayers: ['base','uncertainty','select','pointv','heat','spider','radius','vector'],
        mapSettings: {
            activeLayer: 'none',
            blankDragDropSource: null,
            clusterDistance: SPATIAL_POINT_CLUSTER_DISTANCE,
            clusterPoints: true,
            clusterSource: null,
            defaultSymbology: 'taxa',
            distFromMeLat: null,
            distFromMeLong: null,
            dragDrop1: false,
            dragDrop2: false,
            dragDrop3: false,
            dragDrop4: false,
            dragDrop5: false,
            dragDrop6: false,
            dragDropBorderColor: SPATIAL_DRAGDROP_BORDER_COLOR,
            dragDropBorderWidth: SPATIAL_DRAGDROP_BORDER_WIDTH,
            dragDropFillColor: SPATIAL_DRAGDROP_FILL_COLOR,
            dragDropOpacity: SPATIAL_DRAGDROP_OPACITY,
            dragDropPointRadius: SPATIAL_DRAGDROP_POINT_RADIUS,
            dragDropRasterColorScale: SPATIAL_DRAGDROP_RASTER_COLOR_SCALE,
            dragDropTarget: '',
            draw: null,
            drawToolFreehandMode: false,
            featureCount: 0,
            heatMapBlur: SPATIAL_POINT_HEAT_MAP_BLUR,
            heatMapRadius: SPATIAL_POINT_HEAT_MAP_RADIUS,
            initialMapCenter: SPATIAL_INITIAL_CENTER,
            initialMapZoom: SPATIAL_INITIAL_ZOOM,
            layerQuerySelectorId: null,
            loadPointsError: false,
            loadPointsEvent: false,
            mapSymbology: 'InventoryLevel',
            pointActive: false,
            pointLayerBorderColor: SPATIAL_POINT_BORDER_COLOR,
            pointLayerBorderWidth: SPATIAL_POINT_BORDER_WIDTH,
            pointLayerFillColor: SPATIAL_POINT_FILL_COLOR,
            pointLayerPointRadius: SPATIAL_POINT_POINT_RADIUS,
            pointLayerSelectionsBorderColor: SPATIAL_POINT_SELECTIONS_BORDER_COLOR,
            pointLayerSelectionsBorderWidth: SPATIAL_POINT_SELECTIONS_BORDER_WIDTH,
            pointVectorSource: null,
            polyArea: 0,
            polyCount: 0,
            radiusCircleSource: null,
            rasterAnalysisSource: null,
            recordInfoWindowId: null,
            returnClusters: false,
            selectedBaseLayer: SPATIAL_INITIAL_BASE_LAYER,
            selectedDrawTool: 'None',
            selectedFeatures: null,
            selectedPointFeatures: null,
            selectedRecordsSelectionsSymbologyTab: 'records',
            selectedTargetRaster: 'none',
            selectSource: null,
            shapeActive: false,
            shapesBorderColor: SPATIAL_SHAPES_BORDER_COLOR,
            shapesBorderWidth: SPATIAL_SHAPES_BORDER_WIDTH,
            shapesFillColor: SPATIAL_SHAPES_FILL_COLOR,
            shapesOpacity: SPATIAL_SHAPES_OPACITY,
            shapesPointRadius: SPATIAL_SHAPES_POINT_RADIUS,
            shapesSelectionsBorderColor: SPATIAL_SHAPES_SELECTIONS_BORDER_COLOR,
            shapesSelectionsBorderWidth: SPATIAL_SHAPES_SELECTIONS_BORDER_WIDTH,
            shapesSelectionsFillColor: SPATIAL_SHAPES_SELECTIONS_FILL_COLOR,
            shapesSelectionsOpacity: SPATIAL_SHAPES_SELECTIONS_OPACITY,
            showControlPanelLeft: false,
            showControlPanelTop: true,
            showHeatMap: SPATIAL_POINT_DISPLAY_HEAT_MAP,
            showInfoWindow: false,
            showLayerController: false,
            showLayerQuerySelector: false,
            showMapSettings: false,
            showRecordInfoWindow: false,
            showSidePanel: false,
            sidePanelExpandedElement: 'vector',
            submitButtonDisabled: true,
            submitButtonText: '',
            toggleSelectedPoints: false,
            uncertaintyCircleSource: null,
            uncertaintyRadiusText: '',
            uncertaintyRadiusValue: 0,
            vectorSource: null
        },
        rasterColorScales: [
            {value: 'autumn', label: 'Autumn'},
            {value: 'blackbody', label: 'Blackbody'},
            {value: 'bluered', label: 'Bluered'},
            {value: 'bone', label: 'Bone'},
            {value: 'cool', label: 'Cool'},
            {value: 'copper', label: 'Copper'},
            {value: 'earth', label: 'Earth'},
            {value: 'electric', label: 'Electric'},
            {value: 'greens', label: 'Greens'},
            {value: 'greys', label: 'Greys'},
            {value: 'hot', label: 'Hot'},
            {value: 'hsv', label: 'Hsv'},
            {value: 'inferno', label: 'Inferno'},
            {value: 'jet', label: 'Jet'},
            {value: 'magma', label: 'Magma'},
            {value: 'picnic', label: 'Picnic'},
            {value: 'plasma', label: 'Plasma'},
            {value: 'portland', label: 'Portland'},
            {value: 'rainbow', label: 'Rainbow'},
            {value: 'rdbu', label: 'Rdbu'},
            {value: 'spring', label: 'Spring'},
            {value: 'summer', label: 'Summer'},
            {value: 'turbo', label: 'Turbo'},
            {value: 'viridis', label: 'Viridis'},
            {value: 'winter', label: 'Winter'},
            {value: 'ylgnbu', label: 'Ylgnbu'},
            {value: 'ylorrd', label: 'Ylorrd'}
        ],
        symbologyOptions: [
            {field: 'InventoryLevel', label: 'Inventory Level'},
            {field: 'SurveyStatus', label: 'Survey Status'},
            {field: 'SpringType1', label: 'Spring Type'},
            {field: 'LandUnit', label: 'Land Unit'},
            {field: 'LandUnitDetail', label: 'Land Unit Detail'},
            {field: 'HUC', label: 'HUC'},
            {field: 'infoSource', label: 'Information Source'},
            {field: 'initialtimestamp', label: 'Year Recorded'}
        ]
    }),
    getters: {
        getCoreLayers(state) {
            return state.coreLayers;
        },
        getMapSettings(state) {
            return state.mapSettings;
        },
        getRasterColorScales(state) {
            return state.rasterColorScales;
        },
        getSymbologyOptions(state) {
            return state.symbologyOptions;
        }
    }
});
