<?php
class TaxonRankDataService {

    private $rankData = array(
        'Bacteria' => array(
            array('rankid' => 10, 'rankname' => 'Kingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 20, 'rankname' => 'Subkingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 30, 'rankname' => 'Phylum', 'dirparentrankid' => 20, 'reqparentrankid' => 10),
            array('rankid' => 40, 'rankname' => 'Subphylum', 'dirparentrankid' => 30, 'reqparentrankid' => 30),
            array('rankid' => 50, 'rankname' => 'Superclass', 'dirparentrankid' => 40, 'reqparentrankid' => 30),
            array('rankid' => 60, 'rankname' => 'Class', 'dirparentrankid' => 50, 'reqparentrankid' => 30),
            array('rankid' => 70, 'rankname' => 'Subclass', 'dirparentrankid' => 60, 'reqparentrankid' => 60),
            array('rankid' => 80, 'rankname' => 'Infraclass', 'dirparentrankid' => 70, 'reqparentrankid' => 60),
            array('rankid' => 90, 'rankname' => 'Superorder', 'dirparentrankid' => 80, 'reqparentrankid' => 60),
            array('rankid' => 100, 'rankname' => 'Order', 'dirparentrankid' => 90, 'reqparentrankid' => 60),
            array('rankid' => 110, 'rankname' => 'Suborder', 'dirparentrankid' => 100, 'reqparentrankid' => 100),
            array('rankid' => 120, 'rankname' => 'Infraorder', 'dirparentrankid' => 110, 'reqparentrankid' => 100),
            array('rankid' => 130, 'rankname' => 'Superfamily', 'dirparentrankid' => 120, 'reqparentrankid' => 100),
            array('rankid' => 140, 'rankname' => 'Family', 'dirparentrankid' => 130, 'reqparentrankid' => 100),
            array('rankid' => 150, 'rankname' => 'Subfamily', 'dirparentrankid' => 140, 'reqparentrankid' => 140),
            array('rankid' => 160, 'rankname' => 'Tribe', 'dirparentrankid' => 150, 'reqparentrankid' => 140),
            array('rankid' => 170, 'rankname' => 'Subtribe', 'dirparentrankid' => 160, 'reqparentrankid' => 140),
            array('rankid' => 180, 'rankname' => 'Genus', 'dirparentrankid' => 170, 'reqparentrankid' => 140),
            array('rankid' => 190, 'rankname' => 'Subgenus', 'dirparentrankid' => 180, 'reqparentrankid' => 180),
            array('rankid' => 220, 'rankname' => 'Species', 'dirparentrankid' => 190, 'reqparentrankid' => 180),
            array('rankid' => 230, 'rankname' => 'Subspecies', 'dirparentrankid' => 220, 'reqparentrankid' => 180)
        ),
        'Protozoa' => array(
            array('rankid' => 10, 'rankname' => 'Kingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 20, 'rankname' => 'Subkingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 25, 'rankname' => 'Infrakingdom', 'dirparentrankid' => 20, 'reqparentrankid' => 10),
            array('rankid' => 30, 'rankname' => 'Phylum', 'dirparentrankid' => 25, 'reqparentrankid' => 10),
            array('rankid' => 40, 'rankname' => 'Subphylum', 'dirparentrankid' => 30, 'reqparentrankid' => 30),
            array('rankid' => 45, 'rankname' => 'Infraphylum', 'dirparentrankid' => 40, 'reqparentrankid' => 30),
            array('rankid' => 47, 'rankname' => 'Parvphylum', 'dirparentrankid' => 45, 'reqparentrankid' => 30),
            array('rankid' => 50, 'rankname' => 'Superclass', 'dirparentrankid' => 47, 'reqparentrankid' => 30),
            array('rankid' => 60, 'rankname' => 'Class', 'dirparentrankid' => 50, 'reqparentrankid' => 30),
            array('rankid' => 70, 'rankname' => 'Subclass', 'dirparentrankid' => 60, 'reqparentrankid' => 60),
            array('rankid' => 80, 'rankname' => 'Infraclass', 'dirparentrankid' => 70, 'reqparentrankid' => 60),
            array('rankid' => 90, 'rankname' => 'Superorder', 'dirparentrankid' => 80, 'reqparentrankid' => 60),
            array('rankid' => 100, 'rankname' => 'Order', 'dirparentrankid' => 90, 'reqparentrankid' => 60),
            array('rankid' => 110, 'rankname' => 'Suborder', 'dirparentrankid' => 100, 'reqparentrankid' => 100),
            array('rankid' => 120, 'rankname' => 'Infraorder', 'dirparentrankid' => 110, 'reqparentrankid' => 100),
            array('rankid' => 130, 'rankname' => 'Superfamily', 'dirparentrankid' => 120, 'reqparentrankid' => 100),
            array('rankid' => 140, 'rankname' => 'Family', 'dirparentrankid' => 130, 'reqparentrankid' => 100),
            array('rankid' => 150, 'rankname' => 'Subfamily', 'dirparentrankid' => 140, 'reqparentrankid' => 140),
            array('rankid' => 160, 'rankname' => 'Tribe', 'dirparentrankid' => 150, 'reqparentrankid' => 140),
            array('rankid' => 170, 'rankname' => 'Subtribe', 'dirparentrankid' => 160, 'reqparentrankid' => 140),
            array('rankid' => 180, 'rankname' => 'Genus', 'dirparentrankid' => 170, 'reqparentrankid' => 140),
            array('rankid' => 190, 'rankname' => 'Subgenus', 'dirparentrankid' => 180, 'reqparentrankid' => 180),
            array('rankid' => 220, 'rankname' => 'Species', 'dirparentrankid' => 190, 'reqparentrankid' => 180),
            array('rankid' => 230, 'rankname' => 'Subspecies', 'dirparentrankid' => 220, 'reqparentrankid' => 180),
            array('rankid' => 240, 'rankname' => 'Variety', 'dirparentrankid' => 230, 'reqparentrankid' => 180)
        ),
        'Plantae' => array(
            array('rankid' => 10, 'rankname' => 'Kingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 20, 'rankname' => 'Subkingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 25, 'rankname' => 'Infrakingdom', 'dirparentrankid' => 20, 'reqparentrankid' => 10),
            array('rankid' => 27, 'rankname' => 'Superdivision', 'dirparentrankid' => 25, 'reqparentrankid' => 10),
            array('rankid' => 30, 'rankname' => 'Division', 'dirparentrankid' => 27, 'reqparentrankid' => 10),
            array('rankid' => 40, 'rankname' => 'Subdivision', 'dirparentrankid' => 30, 'reqparentrankid' => 30),
            array('rankid' => 45, 'rankname' => 'Infradivision', 'dirparentrankid' => 40, 'reqparentrankid' => 30),
            array('rankid' => 50, 'rankname' => 'Superclass', 'dirparentrankid' => 45, 'reqparentrankid' => 30),
            array('rankid' => 60, 'rankname' => 'Class', 'dirparentrankid' => 50, 'reqparentrankid' => 30),
            array('rankid' => 70, 'rankname' => 'Subclass', 'dirparentrankid' => 60, 'reqparentrankid' => 60),
            array('rankid' => 80, 'rankname' => 'Infraclass', 'dirparentrankid' => 70, 'reqparentrankid' => 60),
            array('rankid' => 90, 'rankname' => 'Superorder', 'dirparentrankid' => 80, 'reqparentrankid' => 60),
            array('rankid' => 100, 'rankname' => 'Order', 'dirparentrankid' => 90, 'reqparentrankid' => 60),
            array('rankid' => 110, 'rankname' => 'Suborder', 'dirparentrankid' => 100, 'reqparentrankid' => 100),
            array('rankid' => 140, 'rankname' => 'Family', 'dirparentrankid' => 110, 'reqparentrankid' => 100),
            array('rankid' => 150, 'rankname' => 'Subfamily', 'dirparentrankid' => 140, 'reqparentrankid' => 140),
            array('rankid' => 160, 'rankname' => 'Tribe', 'dirparentrankid' => 150, 'reqparentrankid' => 140),
            array('rankid' => 170, 'rankname' => 'Subtribe', 'dirparentrankid' => 160, 'reqparentrankid' => 140),
            array('rankid' => 180, 'rankname' => 'Genus', 'dirparentrankid' => 170, 'reqparentrankid' => 140),
            array('rankid' => 190, 'rankname' => 'Subgenus', 'dirparentrankid' => 180, 'reqparentrankid' => 180),
            array('rankid' => 200, 'rankname' => 'Section', 'dirparentrankid' => 190, 'reqparentrankid' => 180),
            array('rankid' => 210, 'rankname' => 'Subsection', 'dirparentrankid' => 200, 'reqparentrankid' => 180),
            array('rankid' => 220, 'rankname' => 'Species', 'dirparentrankid' => 210, 'reqparentrankid' => 180),
            array('rankid' => 230, 'rankname' => 'Subspecies', 'dirparentrankid' => 220, 'reqparentrankid' => 180),
            array('rankid' => 240, 'rankname' => 'Variety', 'dirparentrankid' => 220, 'reqparentrankid' => 180),
            array('rankid' => 250, 'rankname' => 'Subvariety', 'dirparentrankid' => 240, 'reqparentrankid' => 180),
            array('rankid' => 260, 'rankname' => 'Form', 'dirparentrankid' => 220, 'reqparentrankid' => 180),
            array('rankid' => 270, 'rankname' => 'Subform', 'dirparentrankid' => 260, 'reqparentrankid' => 180),
            array('rankid' => 300, 'rankname' => 'Cultivated', 'dirparentrankid' => 260, 'reqparentrankid' => 180)
        ),
        'Fungi' => array(
            array('rankid' => 10, 'rankname' => 'Kingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 20, 'rankname' => 'Subkingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 30, 'rankname' => 'Division', 'dirparentrankid' => 20, 'reqparentrankid' => 10),
            array('rankid' => 40, 'rankname' => 'Subdivision', 'dirparentrankid' => 30, 'reqparentrankid' => 30),
            array('rankid' => 60, 'rankname' => 'Class', 'dirparentrankid' => 40, 'reqparentrankid' => 30),
            array('rankid' => 70, 'rankname' => 'Subclass', 'dirparentrankid' => 60, 'reqparentrankid' => 60),
            array('rankid' => 90, 'rankname' => 'Superorder', 'dirparentrankid' => 70, 'reqparentrankid' => 60),
            array('rankid' => 100, 'rankname' => 'Order', 'dirparentrankid' => 90, 'reqparentrankid' => 60),
            array('rankid' => 110, 'rankname' => 'Suborder', 'dirparentrankid' => 100, 'reqparentrankid' => 100),
            array('rankid' => 140, 'rankname' => 'Family', 'dirparentrankid' => 110, 'reqparentrankid' => 100),
            array('rankid' => 150, 'rankname' => 'Subfamily', 'dirparentrankid' => 140, 'reqparentrankid' => 140),
            array('rankid' => 160, 'rankname' => 'Tribe', 'dirparentrankid' => 150, 'reqparentrankid' => 140),
            array('rankid' => 170, 'rankname' => 'Subtribe', 'dirparentrankid' => 160, 'reqparentrankid' => 140),
            array('rankid' => 180, 'rankname' => 'Genus', 'dirparentrankid' => 170, 'reqparentrankid' => 140),
            array('rankid' => 190, 'rankname' => 'Subgenus', 'dirparentrankid' => 180, 'reqparentrankid' => 180),
            array('rankid' => 200, 'rankname' => 'Section', 'dirparentrankid' => 190, 'reqparentrankid' => 180),
            array('rankid' => 210, 'rankname' => 'Subsection', 'dirparentrankid' => 200, 'reqparentrankid' => 180),
            array('rankid' => 220, 'rankname' => 'Species', 'dirparentrankid' => 210, 'reqparentrankid' => 180),
            array('rankid' => 230, 'rankname' => 'Subspecies', 'dirparentrankid' => 220, 'reqparentrankid' => 180),
            array('rankid' => 240, 'rankname' => 'Variety', 'dirparentrankid' => 220, 'reqparentrankid' => 180),
            array('rankid' => 250, 'rankname' => 'Subvariety', 'dirparentrankid' => 240, 'reqparentrankid' => 180),
            array('rankid' => 260, 'rankname' => 'Form', 'dirparentrankid' => 220, 'reqparentrankid' => 180),
            array('rankid' => 270, 'rankname' => 'Subform', 'dirparentrankid' => 260, 'reqparentrankid' => 180)
        ),
        'Animalia' => array(
            array('rankid' => 10, 'rankname' => 'Kingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 20, 'rankname' => 'Subkingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 25, 'rankname' => 'Infrakingdom', 'dirparentrankid' => 20, 'reqparentrankid' => 10),
            array('rankid' => 27, 'rankname' => 'Superphylum', 'dirparentrankid' => 25, 'reqparentrankid' => 10),
            array('rankid' => 30, 'rankname' => 'Phylum', 'dirparentrankid' => 27, 'reqparentrankid' => 10),
            array('rankid' => 40, 'rankname' => 'Subphylum', 'dirparentrankid' => 30, 'reqparentrankid' => 30),
            array('rankid' => 45, 'rankname' => 'Infraphylum', 'dirparentrankid' => 40, 'reqparentrankid' => 30),
            array('rankid' => 50, 'rankname' => 'Superclass', 'dirparentrankid' => 45, 'reqparentrankid' => 30),
            array('rankid' => 60, 'rankname' => 'Class', 'dirparentrankid' => 50, 'reqparentrankid' => 30),
            array('rankid' => 70, 'rankname' => 'Subclass', 'dirparentrankid' => 60, 'reqparentrankid' => 60),
            array('rankid' => 80, 'rankname' => 'Infraclass', 'dirparentrankid' => 70, 'reqparentrankid' => 60),
            array('rankid' => 90, 'rankname' => 'Superorder', 'dirparentrankid' => 80, 'reqparentrankid' => 60),
            array('rankid' => 100, 'rankname' => 'Order', 'dirparentrankid' => 90, 'reqparentrankid' => 60),
            array('rankid' => 110, 'rankname' => 'Suborder', 'dirparentrankid' => 100, 'reqparentrankid' => 100),
            array('rankid' => 120, 'rankname' => 'Infraorder', 'dirparentrankid' => 110, 'reqparentrankid' => 100),
            array('rankid' => 124, 'rankname' => 'Section', 'dirparentrankid' => 120, 'reqparentrankid' => 100),
            array('rankid' => 126, 'rankname' => 'Subsection', 'dirparentrankid' => 124, 'reqparentrankid' => 100),
            array('rankid' => 130, 'rankname' => 'Superfamily', 'dirparentrankid' => 126, 'reqparentrankid' => 100),
            array('rankid' => 140, 'rankname' => 'Family', 'dirparentrankid' => 130, 'reqparentrankid' => 100),
            array('rankid' => 150, 'rankname' => 'Subfamily', 'dirparentrankid' => 140, 'reqparentrankid' => 140),
            array('rankid' => 160, 'rankname' => 'Tribe', 'dirparentrankid' => 150, 'reqparentrankid' => 140),
            array('rankid' => 170, 'rankname' => 'Subtribe', 'dirparentrankid' => 160, 'reqparentrankid' => 140),
            array('rankid' => 180, 'rankname' => 'Genus', 'dirparentrankid' => 170, 'reqparentrankid' => 140),
            array('rankid' => 190, 'rankname' => 'Subgenus', 'dirparentrankid' => 180, 'reqparentrankid' => 180),
            array('rankid' => 220, 'rankname' => 'Species', 'dirparentrankid' => 190, 'reqparentrankid' => 180),
            array('rankid' => 230, 'rankname' => 'Subspecies', 'dirparentrankid' => 220, 'reqparentrankid' => 220),
            array('rankid' => 240, 'rankname' => 'Variety', 'dirparentrankid' => 220, 'reqparentrankid' => 220),
            array('rankid' => 245, 'rankname' => 'Form', 'dirparentrankid' => 220, 'reqparentrankid' => 220),
            array('rankid' => 250, 'rankname' => 'Race', 'dirparentrankid' => 220, 'reqparentrankid' => 220),
            array('rankid' => 255, 'rankname' => 'Stirp', 'dirparentrankid' => 220, 'reqparentrankid' => 220),
            array('rankid' => 260, 'rankname' => 'Morph', 'dirparentrankid' => 220, 'reqparentrankid' => 220),
            array('rankid' => 265, 'rankname' => 'Aberration', 'dirparentrankid' => 220, 'reqparentrankid' => 220),
            array('rankid' => 300, 'rankname' => 'Unspecified', 'dirparentrankid' => 220, 'reqparentrankid' => 220)
        ),
        'Chromista' => array(
            array('rankid' => 10, 'rankname' => 'Kingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 20, 'rankname' => 'Subkingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 25, 'rankname' => 'Infrakingdom', 'dirparentrankid' => 20, 'reqparentrankid' => 10),
            array('rankid' => 27, 'rankname' => 'Superdivision', 'dirparentrankid' => 25, 'reqparentrankid' => 10),
            array('rankid' => 30, 'rankname' => 'Division', 'dirparentrankid' => 27, 'reqparentrankid' => 10),
            array('rankid' => 40, 'rankname' => 'Subdivision', 'dirparentrankid' => 30, 'reqparentrankid' => 30),
            array('rankid' => 45, 'rankname' => 'Infradivision', 'dirparentrankid' => 40, 'reqparentrankid' => 30),
            array('rankid' => 47, 'rankname' => 'Parvdivision', 'dirparentrankid' => 45, 'reqparentrankid' => 30),
            array('rankid' => 50, 'rankname' => 'Superclass', 'dirparentrankid' => 47, 'reqparentrankid' => 30),
            array('rankid' => 60, 'rankname' => 'Class', 'dirparentrankid' => 50, 'reqparentrankid' => 30),
            array('rankid' => 70, 'rankname' => 'Subclass', 'dirparentrankid' => 60, 'reqparentrankid' => 60),
            array('rankid' => 80, 'rankname' => 'Infraclass', 'dirparentrankid' => 70, 'reqparentrankid' => 60),
            array('rankid' => 90, 'rankname' => 'Superorder', 'dirparentrankid' => 80, 'reqparentrankid' => 60),
            array('rankid' => 100, 'rankname' => 'Order', 'dirparentrankid' => 90, 'reqparentrankid' => 60),
            array('rankid' => 110, 'rankname' => 'Suborder', 'dirparentrankid' => 100, 'reqparentrankid' => 100),
            array('rankid' => 140, 'rankname' => 'Family', 'dirparentrankid' => 110, 'reqparentrankid' => 100),
            array('rankid' => 150, 'rankname' => 'Subfamily', 'dirparentrankid' => 140, 'reqparentrankid' => 140),
            array('rankid' => 160, 'rankname' => 'Tribe', 'dirparentrankid' => 150, 'reqparentrankid' => 140),
            array('rankid' => 170, 'rankname' => 'Subtribe', 'dirparentrankid' => 160, 'reqparentrankid' => 140),
            array('rankid' => 180, 'rankname' => 'Genus', 'dirparentrankid' => 170, 'reqparentrankid' => 140),
            array('rankid' => 190, 'rankname' => 'Subgenus', 'dirparentrankid' => 180, 'reqparentrankid' => 180),
            array('rankid' => 200, 'rankname' => 'Section', 'dirparentrankid' => 190, 'reqparentrankid' => 180),
            array('rankid' => 210, 'rankname' => 'Subsection', 'dirparentrankid' => 200, 'reqparentrankid' => 180),
            array('rankid' => 220, 'rankname' => 'Species', 'dirparentrankid' => 210, 'reqparentrankid' => 180),
            array('rankid' => 230, 'rankname' => 'Subspecies', 'dirparentrankid' => 220, 'reqparentrankid' => 180),
            array('rankid' => 240, 'rankname' => 'Variety', 'dirparentrankid' => 230, 'reqparentrankid' => 180),
            array('rankid' => 250, 'rankname' => 'Subvariety', 'dirparentrankid' => 240, 'reqparentrankid' => 180),
            array('rankid' => 260, 'rankname' => 'Form', 'dirparentrankid' => 250, 'reqparentrankid' => 180),
            array('rankid' => 270, 'rankname' => 'Subform', 'dirparentrankid' => 260, 'reqparentrankid' => 180)
        ),
        'Archaea' => array(
            array('rankid' => 10, 'rankname' => 'Kingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 20, 'rankname' => 'Subkingdom', 'dirparentrankid' => 10, 'reqparentrankid' => 10),
            array('rankid' => 30, 'rankname' => 'Phylum', 'dirparentrankid' => 20, 'reqparentrankid' => 10),
            array('rankid' => 40, 'rankname' => 'Subphylum', 'dirparentrankid' => 30, 'reqparentrankid' => 30),
            array('rankid' => 50, 'rankname' => 'Superclass', 'dirparentrankid' => 40, 'reqparentrankid' => 30),
            array('rankid' => 60, 'rankname' => 'Class', 'dirparentrankid' => 50, 'reqparentrankid' => 30),
            array('rankid' => 70, 'rankname' => 'Subclass', 'dirparentrankid' => 60, 'reqparentrankid' => 60),
            array('rankid' => 80, 'rankname' => 'Infraclass', 'dirparentrankid' => 70, 'reqparentrankid' => 60),
            array('rankid' => 90, 'rankname' => 'Superorder', 'dirparentrankid' => 80, 'reqparentrankid' => 60),
            array('rankid' => 100, 'rankname' => 'Order', 'dirparentrankid' => 90, 'reqparentrankid' => 60),
            array('rankid' => 110, 'rankname' => 'Suborder', 'dirparentrankid' => 100, 'reqparentrankid' => 100),
            array('rankid' => 120, 'rankname' => 'Infraorder', 'dirparentrankid' => 110, 'reqparentrankid' => 100),
            array('rankid' => 130, 'rankname' => 'Superfamily', 'dirparentrankid' => 120, 'reqparentrankid' => 100),
            array('rankid' => 140, 'rankname' => 'Family', 'dirparentrankid' => 130, 'reqparentrankid' => 100),
            array('rankid' => 150, 'rankname' => 'Subfamily', 'dirparentrankid' => 140, 'reqparentrankid' => 140),
            array('rankid' => 160, 'rankname' => 'Tribe', 'dirparentrankid' => 150, 'reqparentrankid' => 140),
            array('rankid' => 170, 'rankname' => 'Subtribe', 'dirparentrankid' => 160, 'reqparentrankid' => 140),
            array('rankid' => 180, 'rankname' => 'Genus', 'dirparentrankid' => 170, 'reqparentrankid' => 140),
            array('rankid' => 190, 'rankname' => 'Subgenus', 'dirparentrankid' => 180, 'reqparentrankid' => 180),
            array('rankid' => 220, 'rankname' => 'Species', 'dirparentrankid' => 190, 'reqparentrankid' => 180),
            array('rankid' => 230, 'rankname' => 'Subspecies', 'dirparentrankid' => 220, 'reqparentrankid' => 180)
        )
    );

    public static function getDefaultRankOptions(): array
    {
        return array(
            '10' => array('rankname' => 'Kingdom', 'rankid' => 10),
            '20' => array('rankname' => 'Subkingdom', 'rankid' => 20),
            '25' => array('rankname' => 'Infrakingdom', 'rankid' => 25),
            '27' => array('rankname' => 'Superphylum', 'rankid' => 27),
            '30' => array('rankname' => 'Phylum', 'rankid' => 30),
            '40' => array('rankname' => 'Subphylum', 'rankid' => 40),
            '45' => array('rankname' => 'Infraphylum', 'rankid' => 45),
            '50' => array('rankname' => 'Superclass', 'rankid' => 50),
            '60' => array('rankname' => 'Class', 'rankid' => 60),
            '70' => array('rankname' => 'Subclass', 'rankid' => 70),
            '80' => array('rankname' => 'Infraclass', 'rankid' => 80),
            '90' => array('rankname' => 'Superorder', 'rankid' => 90),
            '100' => array('rankname' => 'Order', 'rankid' => 100),
            '110' => array('rankname' => 'Suborder', 'rankid' => 110),
            '120' => array('rankname' => 'Infraorder', 'rankid' => 120),
            '124' => array('rankname' => 'Section', 'rankid' => 124),
            '126' => array('rankname' => 'Subsection', 'rankid' => 126),
            '130' => array('rankname' => 'Superfamily', 'rankid' => 130),
            '140' => array('rankname' => 'Family', 'rankid' => 140),
            '150' => array('rankname' => 'Subfamily', 'rankid' => 150),
            '160' => array('rankname' => 'Tribe', 'rankid' => 160),
            '170' => array('rankname' => 'Subtribe', 'rankid' => 170),
            '180' => array('rankname' => 'Genus', 'rankid' => 180),
            '190' => array('rankname' => 'Subgenus', 'rankid' => 190),
            '220' => array('rankname' => 'Species', 'rankid' => 220),
            '230' => array('rankname' => 'Subspecies', 'rankid' => 230),
            '240' => array('rankname' => 'Variety', 'rankid' => 240),
            '245' => array('rankname' => 'Form', 'rankid' => 245),
            '250' => array('rankname' => 'Race', 'rankid' => 250),
            '255' => array('rankname' => 'Stirp', 'rankid' => 255),
            '260' => array('rankname' => 'Morph', 'rankid' => 260),
            '265' => array('rankname' => 'Aberration', 'rankid' => 265),
            '300' => array('rankname' => 'Unspecified', 'rankid' => 300)
        );
    }

    public function getRankData($kingdomName): array
    {
        return array_key_exists($kingdomName, $this->rankData) ? $this->rankData[$kingdomName] : $this->rankData['Animalia'];
    }
}
