<script type="text/javascript">
    const CLIENT_ROOT = '<?php echo $GLOBALS['CLIENT_ROOT']; ?>';
    const SOLR_MODE = '<?php echo $GLOBALS['SOLR_MODE']; ?>';

    const SPATIAL_INITIAL_ZOOM = <?php echo $GLOBALS['SPATIAL_INITIAL_ZOOM']; ?>;
    const SPATIAL_INITIAL_CENTER = <?php echo $GLOBALS['SPATIAL_INITIAL_CENTER']; ?>;
    const SPATIAL_POINT_FILL_COLOR = '<?php echo $GLOBALS['SPATIAL_POINT_FILL_COLOR']; ?>';
    const SPATIAL_POINT_BORDER_COLOR = '<?php echo $GLOBALS['SPATIAL_POINT_BORDER_COLOR']; ?>';
    const SPATIAL_POINT_BORDER_WIDTH = <?php echo $GLOBALS['SPATIAL_POINT_BORDER_WIDTH']; ?>;
    const SPATIAL_POINT_POINT_RADIUS = <?php echo $GLOBALS['SPATIAL_POINT_POINT_RADIUS']; ?>;
    const SPATIAL_POINT_SELECTIONS_BORDER_COLOR = '<?php echo $GLOBALS['SPATIAL_POINT_SELECTIONS_BORDER_COLOR']; ?>';
    const SPATIAL_POINT_SELECTIONS_BORDER_WIDTH = <?php echo $GLOBALS['SPATIAL_POINT_SELECTIONS_BORDER_WIDTH']; ?>;
    const SPATIAL_SHAPES_FILL_COLOR = '<?php echo $GLOBALS['SPATIAL_SHAPES_FILL_COLOR']; ?>';
    const SPATIAL_SHAPES_BORDER_COLOR = '<?php echo $GLOBALS['SPATIAL_SHAPES_BORDER_COLOR']; ?>';
    const SPATIAL_SHAPES_BORDER_WIDTH = <?php echo $GLOBALS['SPATIAL_SHAPES_BORDER_WIDTH']; ?>;
    const SPATIAL_SHAPES_POINT_RADIUS = <?php echo $GLOBALS['SPATIAL_SHAPES_POINT_RADIUS']; ?>;
    const SPATIAL_SHAPES_OPACITY = '<?php echo $GLOBALS['SPATIAL_SHAPES_OPACITY']; ?>';
    const SPATIAL_SHAPES_SELECTIONS_BORDER_COLOR = '<?php echo $GLOBALS['SPATIAL_SHAPES_SELECTIONS_BORDER_COLOR']; ?>';
    const SPATIAL_SHAPES_SELECTIONS_FILL_COLOR = '<?php echo $GLOBALS['SPATIAL_SHAPES_SELECTIONS_FILL_COLOR']; ?>';
    const SPATIAL_SHAPES_SELECTIONS_BORDER_WIDTH = <?php echo $GLOBALS['SPATIAL_SHAPES_SELECTIONS_BORDER_WIDTH']; ?>;
    const SPATIAL_SHAPES_SELECTIONS_OPACITY = '<?php echo $GLOBALS['SPATIAL_SHAPES_SELECTIONS_OPACITY']; ?>';
    const SPATIAL_DRAGDROP_FILL_COLOR = '<?php echo $GLOBALS['SPATIAL_DRAGDROP_FILL_COLOR']; ?>';
    const SPATIAL_DRAGDROP_BORDER_COLOR = '<?php echo $GLOBALS['SPATIAL_DRAGDROP_BORDER_COLOR']; ?>';
    const SPATIAL_DRAGDROP_BORDER_WIDTH = <?php echo $GLOBALS['SPATIAL_DRAGDROP_BORDER_WIDTH']; ?>;
    const SPATIAL_DRAGDROP_POINT_RADIUS = <?php echo $GLOBALS['SPATIAL_DRAGDROP_POINT_RADIUS']; ?>;
    const SPATIAL_DRAGDROP_OPACITY = '<?php echo $GLOBALS['SPATIAL_DRAGDROP_OPACITY']; ?>';
    const SPATIAL_DRAGDROP_RASTER_COLOR_SCALE = '<?php echo $GLOBALS['SPATIAL_DRAGDROP_RASTER_COLOR_SCALE']; ?>';
</script>
